### ISSUE TITLE
Error after upgrade to V2.0.0

### ISSUE THREAD

**Issue by JLiebstueckel** [felix-mu/geomap-wms-panel#52]
Hi!

I updated the plugin from 1.x to V2.0. Now I'm getting this TypeError if I try to add a new visualization onto a fresh empty dashboard and select "OGC Web Map Service" -> "add WMS". 

Grafana is V11.2.0 and is running in a Docker environment. 

Any idea?

BR
Jens

TypeError: crypto.randomUUID is not a function

    at Va (http://X.X.X.de:3000/public/plugins/felixrelleum-geomapwms-panel/module.js?_cache=2.0.0:2:590043)
    at div
    at div
    at div
    at http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:63:150730
    at div
    at _b (http://X.X.X.de:3000/public/plugins/felixrelleum-geomapwms-panel/module.js?_cache=2.0.0:94:1879)
    at xb (http://X.X.X.de:3000/public/plugins/felixrelleum-geomapwms-panel/module.js?_cache=2.0.0:94:6724)
    at div
    at div
    at div
    at http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:63:150730
    at div
    at div
    at http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:496:1879
    at div
    at div
    at div
    at q (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:859:18761)
    at l (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:63:33933)
    at div
    at div
    at j (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:520:4982)
    at div
    at div
    at ha (http://X.X.X.de:3000/public/build/DashboardPageProxy.3604d9a6305816aecdaf.js:3:2643)
    at div
    at o (http://X.X.X.de:3000/public/build/660.a5b43edd4f587a934f90.js:1:2310)
    at div
    at o (http://X.X.X.de:3000/public/build/660.a5b43edd4f587a934f90.js:1:4298)
    at G (http://X.X.X.de:3000/public/build/660.a5b43edd4f587a934f90.js:1:9639)
    at div
    at div
    at div
    at V (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:229:21920)
    at Ja (http://X.X.X.de:3000/public/build/DashboardPageProxy.3604d9a6305816aecdaf.js:3:14059)
    at Ji (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:1427:122331)
    at WithTheme(Connect(Ja))
    at bs (http://X.X.X.de:3000/public/build/DashboardPageProxy.3604d9a6305816aecdaf.js:3:25337)
    at DashboardPage
    at Ji (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:1427:122331)
    at Ps (http://X.X.X.de:3000/public/build/DashboardPageProxy.3604d9a6305816aecdaf.js:3:32405)
    at Suspense
    at g (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:63:134080)
    at mu (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:4418:11814)
    at I (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:29132)
    at wo (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:4451)
    at ms (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:12000)
    at Vt (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:17388)
    at I (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:31288)
    at div
    at http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:82:52960
    at main
    at div
    at div
    at div
    at Pg (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:4418:2373)
    at div
    at Hc (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:4418:7141)
    at wo (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:4451)
    at ms (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:12000)
    at _s (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:11336)
    at Sr (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:17687)
    at y (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:5:284076)
    at I (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:25385)
    at v (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:164:9002)
    at E (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:1427:112967)
    at o (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:335:27877)
    at g (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:63:134080)
    at a (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:63:134589)
    at ht (http://X.X.X.de:3000/public/build/3855.c53eb219979d7cb3b2d4.js:1431:508)
    at bu (http://X.X.X.de:3000/public/build/3729.ffff83737929c19134ef.js:4418:13861)

**Comment by felix-mu** [comment]
Hi there, thank you for reaching out.
After some research I found this post: https://stackoverflow.com/questions/77980939/typeerror-crypto-randomuuid-is-not-a-function

Referring to your error log I suppose that it is due to that you are not using https nor localhost. So the problem is that crypto.randomUUID only works in secure contexts.

Would you mind testing the plugin using https or just simple localhost?

Nevertheless I might change the randomUUID function since I also found that the use of for list keys is bad practice so I hope I can fix this in a future release.

Best,
Felix

**Comment by felix-mu** [comment]
I just created a pull request. If you want you could build from the main branch the plugin yourself if you don't want to wait for the next plugin release.

**Comment by felix-mu** [comment]
Hi, yes I am going to release a version 2.0.1.
But I am not quite sure when I will manage to do it. Could be in a few weeks maybe.
I hope that is ok.

Best regards,
Felix

**Comment by felix-mu** [comment]
FYI: the plugin submission is in process. It might take some weeks until the plugin v.2.0.1 will be available in the official Grafana Labs Plugin catalog. In the mean time you could manually install the plugin zip from the release page.

Best regards.

**Comment by JLiebstueckel** [comment]
Hi!

Thank you for that info. I don't know how fast Grafana will update their catalog - so, maybe I will use the ZIP.

BR
